#!/bin/bash
# _
#| |__  ___ _ ____      ___ __ ___    _ __ ___
#| '_ \/ __| '_ \ \ /\ / / '_ ` _ \  | '__/ __|
#| |_) \__ \ |_) \ V  V /| | | | | | | | | (__
#|_.__/|___/ .__/ \_/\_/ |_| |_| |_| |_|  \___|
#          |_|
#
# Build: Surface Book 2 
# Version: 1.0

# SOURCE PYWAL COLORS 
. "${HOME}/.cache/wal/colors.sh"

# AUTOSTART
killall -q sxhkd
sxhkd &
killall autolaunch.sh
~/bin/autolaunch.sh &
killall touchy
~/bin/touchy &
sleep 2;
~/bin/padding.sh

# COLORS
background=$color0
foreground=$color7
foreground_alt=$color7
primary=$color1
secondary=$color2
alert=$color3
black=#000000
white=#ffffff
grey=#808080
purple=#DD3CFF

# WORKSPACES
#bspc monitor -d ' dev'  ' www' ' code' ' chat' ' media' ' sys' ' files' ' vbox' ' github' ' email'
#bspc monitor -d '1'  '2' '3' '4' '5' '6' '7' '8' '9' '10'
#bspc monitor -d 'I'  'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII' 'IX' 'X'
#bspc monitor -d 'dev'  'www' 'code' 'chat' 'media' 'sys' 'files' 'vbox' 'github' 'email'
bspc monitor -d ' '  ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' '

# WINDOW SETTINGS
bspc config normal_border_color         $background
bspc config active_border_color         $background
bspc config focused_border_color        $primary
bspc config presel_feedback_color       $primary
center_pseudo_tiled                     true
center_floating                         true
bspc config border_width                2
bspc config window_gap                  2
bspc config focus_follows_pointer       true
bspc config pointer_follows_focus       false

# LAYOUT SETTINGS
bspc config split_ratio                 0.52
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config automatic_scheme longest_side
bspc config initial_polarity second_child

# SCRATCHPAD
bspc rule -a st-256color:scratchy state=floating sticky=on rectangle=2000x1500+0+0 center=true border_width=0

# WINDOW RULES
bspc rule -a st-256color:st-256color rectangle=900x600+0+0 center=true
bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a Krita desktop='^5' state=floating follow=on
bspc rule -a qutebrowser rectangle=2500x1500+0+0 center=true
bspc rule -a firefox state=tiled rectangle=2500x1500+0+0 center=true
bspc rule -a spotify desktop='^5' state=floating rectangle=2500x1500+0+0 center=true
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a st-256color:pulsemixer state=floating rectangle=1000x600+0+0 center=true
bspc rule -a st-256color:ytop state=floating
bspc rule -a st-256color:scratchy state=floating
bspc rule -a Surf state=tiled rectangle=2000x1500+0+0 center=true
bspc rule -a marktext state=tiled rectangle=2000x1500+0+0 center=true
bspc rule -a Sxiv state=floating rectangle=2500x1500+0+0 center=true
bspc rule -a qpaeq state=floating rectangle=1000x400+0+0 center=true
bspc rule -a Pavucontrol state=floating rectangle=1000x1000+0+0 center=true
bspc rule -a Nitrogen state=floating rectangle=1500x1000+0+0 center=true
bspc rule -a Lxappearance state=floating rectangle=1500x1000+0+0 center=true
bspc rule -a Lightdm-settings state=floating rectangle=1500x1000+0+0 center=true
bspc rule -a "Bluetooth Devices" state=floating rectangle=500x500+0+0 center=true
bspc rule -a pcmanfm-qt desktop='^7' state=floating rectangle=1000x1000+0+0 center=true
bspc rule -a "Kvantum Manager" state=floating rectangle=2000x1500+0+0 center=true
bspc rule -a "Network Connections" state=floating rectangle=1500x1000+0+0 center=true
